name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/402989493994/locations/global/workloadIdentityPools/hugo-deploy-pool/attribute.repository/tthomas48/paris-on-the-colorado'
          service_account: 'hugo-deploy@paris-on-the-colorado.iam.gserviceaccount.com'
      - name: Deploy hugo to GCS
        env:
          HUGO_VERSION: 0.120.4
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin          
      - name: Build
        run: |
          hugo      
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public/'
          destination: 'paris-on-the-colorado-website'