name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/402989493994/locations/global/workloadIdentityPools/hugo-deploy-pool'
          service_account: 'hugo-deploy@paris-on-the-colorado.iam.gserviceaccount.com'
      - name: Deploy hugo to GCS
        env:
          HUGO_VERSION: 0.120.4
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin          
      - name: Build
        run: |
          hugo --minify --environment=production
          hugo deploy --target=gcs --environment=production